name: Cypress Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test-material-ui-viewer:
    name: ITK Viewer Material UI Tests
    runs-on: ubuntu-20.04
    container:
      image: cypress/browsers:node16.14.2-slim-chrome103-ff102
      options: --user 1001

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Test with Chrome
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm start

      - name: Test with Firefox
        uses: cypress-io/github-action@v2
        with:
          browser: firefox
          start: npm start


      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "laryssa.abdala@kitware.com"
          npm run semantic-release
