name: Test, Publish

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test-material-ui-viewer:
    name: ITK Viewer Material UI Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.14'

      - name: Install
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Test with Chrome
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          start: npm start

      - name: Test with Electron
        uses: cypress-io/github-action@v4
        with:
          browser: electron
          start: npm start
          config: baseUrl=http://localhost:8081

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "laryssa.abdala@kitware.com"
          npm run semantic-release
